export const KeyPaths = {
    accessKey: "6d5846fd-a4b9-49be-bc1b-0290447b1dcf",
}

export const PagePaths = {
    home: "/",
    about: "/about",
    work: "/work",
    contact: "/contact"
}

export const ImagePaths = {
    hero: "/Hero.png",
    adobePhotoshop: "/Skills/Adobe Photoshop.png",
    aseprite: "/Skills/Aseprite.png",
    bootstrap: "/Skills/Bootstrap.png",
    cSharp: "/Skills/Csharp.png",
    css: "/Skills/CSS.png",
    expressJS: "/Skills/ExpressJS.png",
    git: "/Skills/Git.png",
    hardware: "/Skills/Hardware.png",
    html: "/Skills/HTML.png",
    ink: "/Skills/Inky.png",
    java: "/Skills/Java.png",
    javaScript: "/Skills/JavaScript.png",
    mongoDB: "/Skills/MongoDB.png",
    mySQL: "/Skills/MySQL.png",
    network: "/Skills/Network.png",
    nodeJS: "/Skills/NodeJS.png",
    npm: "/Skills/NPM.png",
    postgreSQL: "/Skills/PostgreSQL.png",
    react: "/Skills/React.png",
    sass: "/Skills/Sass.png",
    server: "/Skills/Server.png",
    tailwindCSS: "/Skills/Tailwind CSS.png",
    unity: "/Skills/Unity.png",
    visualBasic: "/Skills/Visual Basic.png",

    universityOfLuzon: "/UL.png",
    firstRCPE: "/Certificates/1st Research Colloquium & Project Exhibits.png",
    androidAppDev: "/Certificates/Android App Development.png",
    backEndDevAPI: "/Certificates/Back End Development & APIs.png",
    bsitDiploma: "/Certificates/BSIT Diploma.png",
    frontEndDevLib: "/Certificates/Front End Development Libraries.png",
    jsAlgoDS: "/Certificates/JavaScript Algorithms & Data Structures.png",
    relationalDB: "/Certificates/Relational Database.png",
    resWebDes: "/Certificates/Responsive Web Design.png",
    tesdaCSS: "/Certificates/TESDA CSS.png",
    
    jourdansSnackCorner: "/Works/Jourdans Snack Corner.png",
    randomQuoteMachine: "/Works/Random Quote Machine.png",
    drumMachine: "/Works/Drum Machine.png",
    todoApp: "/Works/Todo App.png",
    musicPlayer: "/Works/Music Player.png",
    urlShortener: "/Works/URL Shortener Microservice.png",
    exerciseTracker: "/Works/Exercise Tracker.png",
    pulpRpg: "/Works/PULP RPG.png",
    pulpRpgDoc: "/Works/PULP RPG Documentation.png",
    graphicsDesign: "/Works/Graphics Design.jpg",
    pixelArt: "/Works/Pixel Art.png",
    vbStudentSystem: "",
    mernCrudApp: "",
}

export const ExternalPaths = {
    resume: "/Carlos Johncent Ventura Resume.pdf",
    facebook: "https://www.facebook.com/johncent.ventura.7",
    github: "https://github.com/JohncentVentura",
    pinterest: "https://ph.pinterest.com/johncentventura/pins/",

    adobePhotoshop: "https://www.adobe.com/products/photoshop.html",
    aseprite: "https://aseprite.org/",
    bootstrap: "https://getbootstrap.com/",
    cSharp: "https://docs.unity3d.com/Manual/ScriptingSection.html",
    css: "https://www.w3schools.com/css/",
    expressJS: "https://expressjs.com/",
    git: "https://www.git-scm.com/",
    hardware: "https://e-tesda.gov.ph/course/index.php?categoryid=16",
    html: "https://www.w3schools.com/html/",
    ink: "https://www.inklestudios.com/ink/",
    java: "https://www.java.com/en/",
    javaScript: "https://www.javascript.com/",
    mongoDB: "https://www.mongodb.com/lp/cloud/atlas/try4?utm_content=rlsavisitor&utm_source=google&utm_campaign=search_gs_pl_evergreen_atlas_core_retarget-brand_gic-null_apac-all_ps-all_desktop_eng_lead&utm_term=mongodb&utm_medium=cpc_paid_search&utm_ad=e&utm_ad_campaign_id=14412646476&adgroup=131761130812&cq_cmp=14412646476&gad_source=1&gclid=CjwKCAjwmrqzBhAoEiwAXVpgornjh4oe2dVT2egalczl2pdA7xmoUyvedcKuWd1eIwq-mxSg8y-rkhoCcH4QAvD_BwE",
    mySQL: "https://www.mysql.com/",
    network: "https://e-tesda.gov.ph/course/index.php?categoryid=16",
    nodeJS: "https://nodejs.org/en",
    npm: "https://www.npmjs.com/",
    postgreSQL: "https://www.postgresql.org/",
    react: "https://react.dev/",
    sass: "https://sass-lang.com/",
    server: "https://e-tesda.gov.ph/course/index.php?categoryid=16",
    tailwindCSS: "https://tailwindcss.com/",
    unity: "https://unity.com/",
    visualBasic: "https://learn.microsoft.com/en-us/dotnet/visual-basic/",

    freeCodeCamp: "https://www.freecodecamp.org/learn/",
    universityOfLuzon: "https://ul.edu.ph/",
    firstRCPE: "",
    androidAppDev: "",
    backEndDevAPI: "https://www.freecodecamp.org/certification/Johncent-Developer/back-end-development-and-apis",
    bsitDiploma: "https://www.facebook.com/photo/?fbid=616436970579239&set=a.427670096122595",
    frontEndDevLib: "https://www.freecodecamp.org/certification/Johncent-Developer/front-end-development-libraries",
    jsAlgoDS: "https://www.freecodecamp.org/certification/Johncent-Developer/javascript-algorithms-and-data-structures",
    relationalDB: "https://www.freecodecamp.org/certification/Johncent-Developer/relational-database-v8",
    resWebDes: "https://www.freecodecamp.org/certification/Johncent-Developer/responsive-web-design",
    tesdaCSS: "https://www.facebook.com/photo?fbid=387383134255760&set=pcb.387388560921884",

    jourdansSnackCorner: "https://jourdans-snack-corner.netlify.app",
    gitJourdansSnackCorner: "https://github.com/JohncentVentura/Jourdans-Snack-Corner",
    randomQuoteMachine: "https://cjv-random-quote-machine.netlify.app",
    gitRandomQuoteMachine: "https://github.com/JohncentVentura/Random-Quote-Machine",
    drumMachine: "https://cjv-drum-machine.netlify.app",
    gitDrumMachine: "https://github.com/JohncentVentura/Drum-Machine",
    todoApp: "https://cjv-todo-app.netlify.app",
    gitTodoApp: "https://github.com/JohncentVentura/Todo-App",
    musicPlayer: "https://cjv-music-player.netlify.app",
    gitMusicPlayer: "https://github.com/JohncentVentura/Music-Player",
    urlShortener: "https://url-shortener-microservice-frse.onrender.com",
    gitUrlShortener: "https://github.com/JohncentVentura/URL-Shortener-Microservice",
    exerciseTracker: "https://exercise-tracker-9k5u.onrender.com",
    gitExerciseTracker: "https://github.com/JohncentVentura/Exercise-Tracker",
    pulpRpg: "https://drive.google.com/file/d/1UoWxtuWfohXF-6YLGBBe0MQ9s2_f3GDN/view?usp=sharing",
    gitPulpRpg: "https://github.com/JohncentVentura/PULP-RPG-Scripts",
    pulpRpgDoc: "https://pulp-rpg-doc.netlify.app",
    gitPulpRpgDoc: "https://github.com/JohncentVentura/PULP-RPG-Documentation",
    graphicsDesign: "https://ph.pinterest.com/johncentventura/graphics-design/  ",
    pixelArt: "https://ph.pinterest.com/johncentventura/pixel-art/",
    vbStudentSystem: "",
    gitVbStudentSystem: "https://github.com/JohncentVentura/Student-Registration-System",
    mernCrudApp: "",
    gitMernCrudApp: "https://github.com/JohncentVentura/MERN-CRUD-APP",

    phone: "tel:0956-419-6962",
    email: "mailto:johncent.ventura@gmail.com",
    address: "https://www.google.com/maps/place/Pozorrubio,+Pangasinan/@16.1134395,120.48211,13z/data=!3m1!4b1!4m6!3m5!1s0x33916cb5f40f6be3:0xeabbbddf910cf96c!8m2!3d16.1163874!4d120.5431187!16zL20vMDZqemxx?entry=ttu",
}